#!/usr/bin/env python3
"""Interactively generate a local, capability-resolved AGENTS.md."""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable


SCHEMA_VERSION = 1
PRESETS = ("readonly", "curate-on-use", "autonomous", "maintainer")
PRESET_LABELS = {
    "readonly": "只读：本地查询和联网核验，不持久修改仓库",
    "curate-on-use": "按需整理：可整理本次实际使用的现有原件",
    "autonomous": "自主补全：可搜索、下载并整理当前任务缺失资料",
    "maintainer": "维护：可进行主动质量维护，重大变更仍需确认",
}
PRESET_FRAGMENTS = {
    "readonly": ("common.md", "read-only.md"),
    "curate-on-use": ("common.md", "curation.md"),
    "autonomous": ("common.md", "curation.md", "acquisition.md"),
    "maintainer": (
        "common.md",
        "curation.md",
        "acquisition.md",
        "maintenance.md",
    ),
}


class ConfigurationError(ValueError):
    """Raised when the local configuration is invalid."""


@dataclass(frozen=True)
class AgentConfiguration:
    preset: str
    auto_commit: bool
    auto_push: bool

    def as_dict(self) -> dict[str, object]:
        return {
            "schema_version": SCHEMA_VERSION,
            "preset": self.preset,
            "git": {
                "auto_commit": self.auto_commit,
                "auto_push": self.auto_push,
            },
        }


class PolicyGenerator:
    def __init__(self, root: Path, policy_dir: Path | None = None) -> None:
        self.root = root.resolve()
        self.policy_dir = (
            policy_dir.resolve()
            if policy_dir is not None
            else self.root / "agent-policy"
        )
        self.config_path = self.root / ".agent-mode.json"
        self.prompt_path = self.root / "AGENTS.md"

    def parse_configuration(self, raw: object) -> AgentConfiguration:
        if not isinstance(raw, dict):
            raise ConfigurationError("配置根节点必须是 JSON 对象")
        if set(raw) != {"schema_version", "preset", "git"}:
            raise ConfigurationError(
                "顶层字段必须且只能是 schema_version、preset、git"
            )
        if raw["schema_version"] != SCHEMA_VERSION:
            raise ConfigurationError(
                f"schema_version 必须为 {SCHEMA_VERSION}"
            )
        preset = raw["preset"]
        if not isinstance(preset, str) or preset not in PRESETS:
            raise ConfigurationError(
                "preset 必须是 readonly、curate-on-use、autonomous 或 maintainer"
            )
        git = raw["git"]
        if not isinstance(git, dict) or set(git) != {
            "auto_commit",
            "auto_push",
        }:
            raise ConfigurationError(
                "git 必须且只能包含 auto_commit 和 auto_push"
            )
        auto_commit = git["auto_commit"]
        auto_push = git["auto_push"]
        if type(auto_commit) is not bool or type(auto_push) is not bool:
            raise ConfigurationError("auto_commit 和 auto_push 必须是布尔值")
        if auto_push and not auto_commit:
            raise ConfigurationError(
                "auto_push: true 要求 auto_commit: true"
            )
        if preset == "readonly" and (auto_commit or auto_push):
            raise ConfigurationError(
                "readonly 预设不允许自动提交或推送"
            )
        return AgentConfiguration(preset, auto_commit, auto_push)

    def load_configuration(self) -> AgentConfiguration:
        try:
            raw = json.loads(self.config_path.read_text(encoding="utf-8"))
        except FileNotFoundError as exc:
            raise ConfigurationError("未找到 .agent-mode.json") from exc
        except json.JSONDecodeError as exc:
            raise ConfigurationError(
                f".agent-mode.json 不是合法 JSON：{exc.msg}"
            ) from exc
        return self.parse_configuration(raw)

    def render(self, config: AgentConfiguration) -> str:
        fragment_names = list(PRESET_FRAGMENTS[config.preset])
        if config.preset != "readonly":
            if not config.auto_commit:
                fragment_names.append("git-worktree-only.md")
            elif config.auto_push:
                fragment_names.append("git-commit-push.md")
            else:
                fragment_names.append("git-local-commit.md")

        fragments: list[str] = []
        for name in fragment_names:
            path = self.policy_dir / name
            try:
                text = path.read_text(encoding="utf-8").strip()
            except FileNotFoundError as exc:
                raise ConfigurationError(f"缺少策略分片：{path}") from exc
            if not text:
                raise ConfigurationError(f"策略分片为空：{path}")
            fragments.append(text)

        header = (
            "# Agent Instructions\n\n"
            "This file is generated by the repository setup tool. "
            "Do not edit or replace it."
        )
        return header + "\n\n" + "\n\n".join(fragments) + "\n"

    def serialized_configuration(self, config: AgentConfiguration) -> str:
        return (
            json.dumps(config.as_dict(), ensure_ascii=False, indent=2) + "\n"
        )

    @staticmethod
    def _temporary_file(path: Path, content: str) -> Path:
        path.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
            return Path(handle.name)

    @staticmethod
    def _restore(path: Path, previous: bytes | None) -> None:
        if previous is None:
            path.unlink(missing_ok=True)
            return
        temporary = PolicyGenerator._temporary_file(
            path, previous.decode("utf-8")
        )
        os.replace(temporary, path)

    def write(
        self,
        config: AgentConfiguration,
        replace: Callable[[Path, Path], None] = os.replace,
    ) -> None:
        config_text = self.serialized_configuration(config)
        prompt_text = self.render(config)
        previous_config = (
            self.config_path.read_bytes() if self.config_path.exists() else None
        )
        previous_prompt = (
            self.prompt_path.read_bytes() if self.prompt_path.exists() else None
        )
        config_temp = self._temporary_file(self.config_path, config_text)
        prompt_temp = self._temporary_file(self.prompt_path, prompt_text)

        try:
            replace(config_temp, self.config_path)
            replace(prompt_temp, self.prompt_path)
        except Exception:
            config_temp.unlink(missing_ok=True)
            prompt_temp.unlink(missing_ok=True)
            self._restore(self.config_path, previous_config)
            self._restore(self.prompt_path, previous_prompt)
            raise

    def check(self) -> tuple[bool, str]:
        try:
            config = self.load_configuration()
            expected = self.render(config)
        except ConfigurationError as exc:
            return False, str(exc)
        try:
            actual = self.prompt_path.read_text(encoding="utf-8")
        except FileNotFoundError:
            return False, "未找到生成的 AGENTS.md"
        if actual != expected:
            return False, "AGENTS.md 与当前配置不一致，请重新运行配置工具"
        return True, "配置和 AGENTS.md 一致"


def ask_yes_no(question: str, default: bool) -> bool:
    suffix = "[Y/n]" if default else "[y/N]"
    while True:
        answer = input(f"{question} {suffix} ").strip().lower()
        if not answer:
            return default
        if answer in {"y", "yes", "是"}:
            return True
        if answer in {"n", "no", "否"}:
            return False
        print("请输入 y 或 n。")


def choose_preset() -> str:
    print("\n请选择 Agent 权限预设：")
    for index, preset in enumerate(PRESETS, start=1):
        print(f"  {index}. {PRESET_LABELS[preset]}")
    while True:
        answer = input("输入序号 [1-4]：").strip()
        if answer in {"1", "2", "3", "4"}:
            return PRESETS[int(answer) - 1]
        print("请输入 1、2、3 或 4。")


def configure_interactively(
    generator: PolicyGenerator,
) -> AgentConfiguration | None:
    current: AgentConfiguration | None = None
    if generator.config_path.exists():
        try:
            current = generator.load_configuration()
        except ConfigurationError as exc:
            print(f"现有配置无效：{exc}")
        else:
            print("当前配置：")
            print(f"  权限：{PRESET_LABELS[current.preset]}")
            print(f"  自动提交：{current.auto_commit}")
            print(f"  自动推送：{current.auto_push}")
            if ask_yes_no("保持当前配置并重新生成提示词？", True):
                return current

    preset = choose_preset()
    if preset == "readonly":
        auto_commit = False
        auto_push = False
    else:
        auto_commit = ask_yes_no("完成有效改动后自动创建本地提交？", False)
        auto_push = (
            ask_yes_no("自动推送任务开始时所在的当前分支？", False)
            if auto_commit
            else False
        )
    return AgentConfiguration(preset, auto_commit, auto_push)


def print_summary(generator: PolicyGenerator, config: AgentConfiguration) -> None:
    prompt_size = len(generator.render(config).encode("utf-8"))
    print("\n将生成以下本地设置：")
    print(f"  权限：{PRESET_LABELS[config.preset]}")
    print(f"  自动提交：{config.auto_commit}")
    print(f"  自动推送：{config.auto_push}")
    print(f"  提示词大小：{prompt_size} bytes")
    print(f"  配置：{generator.config_path}")
    print(f"  提示词：{generator.prompt_path}")
    if config.auto_push:
        print("  注意：生成的规则允许 Agent 提交并修改远端当前分支。")
    elif config.auto_commit:
        print("  注意：生成的规则允许 Agent 创建本地提交，但禁止推送。")


def run_interactive(generator: PolicyGenerator) -> int:
    try:
        config = configure_interactively(generator)
        if config is None:
            return 1
        print_summary(generator, config)
        if not ask_yes_no("确认写入或替换这些本地文件？", False):
            print("已取消，未修改文件。")
            return 1
        generator.write(config)
    except (ConfigurationError, OSError) as exc:
        print(f"生成失败：{exc}", file=sys.stderr)
        return 2

    print("配置和 AGENTS.md 已生成。")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="配置并生成当前 checkout 的本地 AGENTS.md"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="只检查本地配置与生成提示词是否一致",
    )
    args = parser.parse_args(argv)

    root = Path(__file__).resolve().parent
    generator = PolicyGenerator(root)
    if args.check:
        valid, message = generator.check()
        print(message)
        return 0 if valid else 2

    return run_interactive(generator)


if __name__ == "__main__":
    raise SystemExit(main())
